"""Hardware attestation: block-hash-seeded toy runs, the reference executor,
and timed verdicts."""

from .challenge import (
    ATTEST_DOMAIN,
    DEFAULT_DEADLINE_S,
    DEFAULT_INNER_STEPS,
    AttestationChallenge,
    challenge_run_config,
    derive_expected,
    make_challenge,
    toy4l_overlay,
)
from .reference_step import (
    ATTEST_DATA_DOMAIN,
    ATTEST_DATA_WORLD_SIZE,
    ATTEST_NUM_SHARDS,
    ATTEST_UID,
    ATTEST_WINDOW,
    AttestationResponse,
    attestation_manifest,
    attestation_run_seed,
    attestation_state_root,
    run_reference,
    write_attestation_shards,
)
from .verify import (
    REATTEST_DOMAIN,
    AttestationVerdict,
    Verifier,
    judge,
    schedule_reattestation,
)

__all__ = [
    "ATTEST_DATA_DOMAIN",
    "ATTEST_DATA_WORLD_SIZE",
    "ATTEST_DOMAIN",
    "ATTEST_NUM_SHARDS",
    "ATTEST_UID",
    "ATTEST_WINDOW",
    "DEFAULT_DEADLINE_S",
    "DEFAULT_INNER_STEPS",
    "REATTEST_DOMAIN",
    "AttestationChallenge",
    "AttestationResponse",
    "AttestationVerdict",
    "Verifier",
    "attestation_manifest",
    "attestation_run_seed",
    "attestation_state_root",
    "challenge_run_config",
    "derive_expected",
    "judge",
    "make_challenge",
    "run_reference",
    "schedule_reattestation",
    "toy4l_overlay",
    "write_attestation_shards",
]
