"""Dataprep pipeline stages: tokenizer training, download spools, dedup,
tokenize+pack, shard writing, manifest building, upload, verification."""

from .build_manifest import (
    MANIFEST_FILENAME,
    SHARD_INDEX_FILENAME,
    TOKENIZER_FILENAME,
    build_dataset_manifest,
    load_manifest_ref,
    load_shard_index,
)
from .dedup import DedupStats, dedup_documents, doc_digest, normalize
from .download import (
    CorpusConfig,
    SourceSpec,
    SpoolState,
    download_corpus,
    download_source,
    iter_source_documents,
    load_corpus_config,
    load_spool_state,
    spool_documents,
)
from .shard_writer import (
    FULL_SHARD_SEQUENCES,
    SHARD_METAS_FILENAME,
    ShardMeta,
    load_shard_metas,
    save_shard_metas,
    write_shards,
)
from .tokenize_pack import (
    MAX_TOKEN_ID,
    chunk_token_arrays,
    chunk_token_stream,
    encode_documents,
    iter_token_file_arrays,
    pack_documents,
    write_token_stream,
)
from .tokenizer_train import (
    BOS_ID,
    BOS_TOKEN,
    EOS_ID,
    EOS_TOKEN,
    PAD_ID,
    PAD_TOKEN,
    TokenizerConfig,
    TrainedTokenizer,
    load_tokenizer_config,
    tokenizer_file_hash,
    train_tokenizer,
)
from .upload import UploadReport, dataset_files, resolve_endpoint, upload_dataset, upload_dataset_sync
from .verify import VerifyReport, verify_local, verify_sample

__all__ = [
    "BOS_ID",
    "BOS_TOKEN",
    "EOS_ID",
    "EOS_TOKEN",
    "FULL_SHARD_SEQUENCES",
    "MANIFEST_FILENAME",
    "MAX_TOKEN_ID",
    "PAD_ID",
    "PAD_TOKEN",
    "SHARD_INDEX_FILENAME",
    "SHARD_METAS_FILENAME",
    "TOKENIZER_FILENAME",
    "CorpusConfig",
    "DedupStats",
    "ShardMeta",
    "SourceSpec",
    "SpoolState",
    "TokenizerConfig",
    "TrainedTokenizer",
    "UploadReport",
    "VerifyReport",
    "build_dataset_manifest",
    "chunk_token_arrays",
    "chunk_token_stream",
    "dataset_files",
    "dedup_documents",
    "doc_digest",
    "normalize",
    "download_corpus",
    "download_source",
    "encode_documents",
    "iter_source_documents",
    "iter_token_file_arrays",
    "load_corpus_config",
    "load_manifest_ref",
    "load_shard_index",
    "load_shard_metas",
    "load_spool_state",
    "load_tokenizer_config",
    "pack_documents",
    "resolve_endpoint",
    "save_shard_metas",
    "spool_documents",
    "tokenizer_file_hash",
    "train_tokenizer",
    "upload_dataset",
    "upload_dataset_sync",
    "verify_local",
    "verify_sample",
    "write_shards",
    "write_token_stream",
]
