"""The interim-release fork (playbook step C: "around 1.5T tokens, fork a
branch for an early anneal + release ('v0.9') while the main branch keeps
training").

A fork is nothing but a MANIFEST operation: starting from a lineage checkpoint
(which holds θ_start of `meta.window + 1`), append a phase amendment that
switches the data tree to the anneal set and the LR to a `wsd_linear_decay`
segment starting at the fork point. The D-branch fleet then runs the SAME
`C` applications against the forked manifest; the main branch keeps the
original manifest and never notices.

The decay segment encodes its start as `LRSpec.warmup_steps` — the global
inner step at which the amendment takes effect (the `lr_at` closed form
measures decay progress from there in tokens; see C/core/phase.py and
ENGINEERING_NOTES). That step is derived with the consensus accounting
function `run_state_at`, which is why this module requires the run's
`RunConfig` alongside the manifest.

Outputs in `out_dir`:
  - `manifest.json`   — canonical bytes of the forked RunManifest (its file
                        hash IS the manifest_hash to commit on-chain)
  - `RELEASE_FORK.md` — the operator runbook: launch the D-branch fleet vs
                        continue the main branch

CLI:  python -m D.release_fork --checkpoint DIR --out DIR --manifest PATH \
          --config C/configs/base.yaml [--overlay ...] --decay-tokens N \
          --effective-window W --committed-block B [--anneal-dataset anneal]
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path

from C.core.checkpoint import CheckpointMeta
from C.core.phase import resolve_phase
from C.core.window_runner import run_state_at
from mok_core.config import LRSpec, RunConfig
from mok_core.config.canonical import canonical_bytes, config_hash
from mok_core.config.loader import load_run_config
from mok_core.config.manifest import PhaseEntry, PhaseOverrides, RunManifest

MANIFEST_FILENAME = "manifest.json"
RUNBOOK_FILENAME = "RELEASE_FORK.md"
DEFAULT_PHASE_NAME = "anneal_release"
META_FILENAME = "meta.json"

RUNBOOK_TEMPLATE = """\
# Interim-release fork runbook — {phase_name} @ window {effective_window}

Generated by `D/release_fork.py`. This fork branches run `{run_id}` at the
window-{checkpoint_window} checkpoint into an anneal-and-release lineage
(playbook: "interim release fork at ~1.5T tokens") while the MAIN branch keeps
training on the original manifest.

## Fork facts (verify before launching anything)

| Field | Value |
|---|---|
| Source run | `{run_id}` |
| Fork run id | `{fork_run_id}` |
| Fork checkpoint | window {checkpoint_window} (holds θ_start of window {resume_window}) |
| Checkpoint state_root | `{state_root}` |
| Original manifest_hash | `{original_manifest_hash}` |
| **Forked manifest_hash** | `{forked_manifest_hash}` |
| Anneal dataset | `{anneal_dataset}` (merkle root `{anneal_merkle_root}`) |
| Amendment effective window | {effective_window} |
| Decay start (global inner step) | {decay_start_step} |
| Decay budget | {decay_tokens:,} tokens (peak {peak_lr} -> 0, wsd_linear_decay) |
| Amendment committed at block | {committed_block} |

## A. Launch the D-branch (release) fleet

1. Owner: commit the forked manifest hash on-chain for the release branch
   (`ManifestCommit`), then distribute `manifest.json` from this directory.
   `blake2b-256(manifest.json)` must equal `{forked_manifest_hash}`.
2. Every D-branch node: verify the local file hash matches the on-chain
   commitment, then restore the fork checkpoint:
   - download the window-{checkpoint_window} checkpoint,
   - load it and assert `state_root == {state_root}` BEFORE the first window.
3. Launch the standard step-C applications against the forked manifest inside
   the blessed container (same digest — the fork changes data + LR only):

       ./C/scripts/run_miner.sh      --manifest {manifest_filename}
       ./C/scripts/run_validator.sh  --manifest {manifest_filename}
       ./C/scripts/run_auditor.sh    --manifest {manifest_filename}

   From window {effective_window} the phase table switches every node to the
   `{anneal_dataset}` shard tree with the decaying LR — no code or config
   change, no restart flag (`requires_restart` is false: same shapes).
4. Windows {resume_window}..{decay_end_hint} anneal to LR 0. Audits, scoring
   and certificates run EXACTLY as in bulk — release weights stay replay-
   verifiable end to end.
5. At LR ~0: final checkpoint -> `F/convert_dcp_to_hf.py` (parity gate) ->
   step-H provenance bundle + release ("v0.9").

## B. Continue the MAIN branch (nothing to do)

The main fleet keeps the ORIGINAL manifest (`{original_manifest_hash}`) and
keeps training at flat LR toward the full anneal. Do NOT ship the forked
manifest to main-branch nodes; the two lineages are distinguished on-chain by
their manifest hashes. Miners may run only one branch per registered UID.

## Abort

If the fork misbehaves before any release artifact ships: stop the D-branch
fleet and delete its buckets' window objects. The main branch was never
touched; no rollback vote is needed.
"""


@dataclass(frozen=True)
class ForkResult:
    """Everything `fork_release` produced. `manifest` is the forked RunManifest."""

    manifest: RunManifest
    manifest_path: Path
    runbook_path: Path
    decay_start_step: int
    peak_lr: float


class ForkError(ValueError):
    """A precondition of the fork procedure failed."""


def load_checkpoint_meta(checkpoint_dir: str | Path) -> CheckpointMeta:
    """Read `meta.json` from a checkpoint directory (the C/core/checkpoint layout)."""
    meta_path = Path(checkpoint_dir) / META_FILENAME
    if not meta_path.is_file():
        raise ForkError(f"no {META_FILENAME} in {checkpoint_dir} — not a checkpoint directory")
    return CheckpointMeta.from_dict(json.loads(meta_path.read_text(encoding="utf-8")))


def _resolve_peak_lr(manifest: RunManifest, cfg: RunConfig, effective_window: int) -> float:
    """The LR level the anneal decays FROM: the spec active just before the fork."""
    prior = resolve_phase(manifest, cfg, max(effective_window - 1, 0)).lr
    if prior.kind == "const":
        return float(prior.const_lr)  # validated non-None by LRSpec
    return prior.peak_lr


def fork_release(
    checkpoint_dir: str | Path,
    out_dir: str | Path,
    *,
    manifest: RunManifest,
    cfg: RunConfig,
    anneal_dataset: str = "anneal",
    decay_tokens: int,
    effective_window: int,
    committed_block: int,
    phase_name: str = DEFAULT_PHASE_NAME,
    fork_run_id: str | None = None,
) -> ForkResult:
    """Fork the run at `checkpoint_dir` into an anneal-and-release manifest.

    Pure with respect to `manifest` (a NEW amended RunManifest is returned; the
    input object is never mutated) and idempotence-safe (refuses to overwrite
    an existing `out_dir/manifest.json`).

    `cfg` must be the run's exact RunConfig (checked against
    `manifest.config_hash`) — it anchors the consensus derivation of the decay
    start step via `run_state_at`.
    """
    meta = load_checkpoint_meta(checkpoint_dir)

    if config_hash(cfg) != manifest.config_hash:
        raise ForkError(
            "RunConfig does not hash to manifest.config_hash — the decay-start derivation "
            "would not be the consensus one. Pass the run's exact config."
        )
    if meta.manifest_hash != manifest.manifest_hash():
        raise ForkError(
            f"checkpoint binds manifest {meta.manifest_hash} but the supplied manifest hashes to "
            f"{manifest.manifest_hash()} — wrong lineage or an unamended/over-amended manifest"
        )
    if decay_tokens <= 0:
        raise ForkError(f"decay_tokens must be positive, got {decay_tokens}")
    if effective_window <= meta.window:
        raise ForkError(
            f"effective_window {effective_window} must be after the fork checkpoint (window "
            f"{meta.window} holds θ_start of window {meta.window + 1})"
        )
    if committed_block < 0:
        raise ForkError(f"committed_block must be >= 0, got {committed_block}")
    try:
        anneal_ref = manifest.dataset(anneal_dataset)
    except KeyError as exc:
        raise ForkError(
            f"dataset {anneal_dataset!r} is not in the manifest — publish the anneal shard tree "
            "(step A, corpus_anneal) and amend the manifest datasets first"
        ) from exc

    # Consensus decay start: the global inner step at the amendment's window.
    decay_start = run_state_at(cfg, manifest, effective_window, world_size=cfg.model.ep_size)
    peak_lr = _resolve_peak_lr(manifest, cfg, effective_window)
    anneal_lr = LRSpec(
        kind="wsd_linear_decay",
        peak_lr=peak_lr,
        warmup_steps=decay_start.global_inner_step,  # decay begins here (see lr_at)
        decay_total_tokens=decay_tokens,
    )
    phase = PhaseEntry(
        start_window=effective_window,
        name=phase_name,
        overrides=PhaseOverrides(data=anneal_dataset, lr=anneal_lr),
    )
    forked = manifest.with_amendment(
        kind="phase",
        effective_window=effective_window,
        committed_block=committed_block,
        phase=phase,
    )
    if fork_run_id is not None:
        forked = RunManifest.model_validate(forked.model_dump() | {"run_id": fork_run_id})

    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    manifest_path = out / MANIFEST_FILENAME
    if manifest_path.exists():
        raise FileExistsError(f"{manifest_path} already exists — refusing to overwrite a published fork")
    manifest_path.write_bytes(canonical_bytes(forked))  # file hash == manifest_hash

    tokens_per_window = cfg.tokens_per_inner_step * resolve_phase(forked, cfg, effective_window).inner_steps
    decay_windows = max(1, decay_tokens // max(tokens_per_window, 1))
    runbook_path = out / RUNBOOK_FILENAME
    runbook_path.write_text(
        RUNBOOK_TEMPLATE.format(
            phase_name=phase_name,
            run_id=manifest.run_id,
            fork_run_id=forked.run_id,
            checkpoint_window=meta.window,
            resume_window=meta.window + 1,
            state_root=meta.state_root,
            original_manifest_hash=manifest.manifest_hash(),
            forked_manifest_hash=forked.manifest_hash(),
            anneal_dataset=anneal_dataset,
            anneal_merkle_root=anneal_ref.merkle_root,
            effective_window=effective_window,
            decay_start_step=decay_start.global_inner_step,
            decay_tokens=decay_tokens,
            peak_lr=peak_lr,
            committed_block=committed_block,
            manifest_filename=MANIFEST_FILENAME,
            decay_end_hint=effective_window + decay_windows,
        ),
        encoding="utf-8",
    )
    return ForkResult(
        manifest=forked,
        manifest_path=manifest_path,
        runbook_path=runbook_path,
        decay_start_step=decay_start.global_inner_step,
        peak_lr=peak_lr,
    )


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m D.release_fork",
        description="Fork the run into an interim-release anneal branch (manifest amendment + runbook).",
    )
    parser.add_argument("--checkpoint", required=True, help="checkpoint directory (contains meta.json)")
    parser.add_argument("--out", required=True, help="output directory for manifest.json + RELEASE_FORK.md")
    parser.add_argument("--manifest", required=True, help="path to the CURRENT run manifest JSON")
    parser.add_argument("--config", required=True, help="RunConfig base YAML (e.g. C/configs/base.yaml)")
    parser.add_argument("--overlay", action="append", default=[], help="config overlay YAML (repeatable)")
    parser.add_argument("--decay-tokens", type=int, required=True, help="anneal budget (e.g. 150e9 for v0.9)")
    parser.add_argument("--effective-window", type=int, required=True, help=">= 2 windows ahead of chain head")
    parser.add_argument("--committed-block", type=int, required=True, help="block the amendment commits at")
    parser.add_argument("--anneal-dataset", default="anneal", help="DatasetManifestRef.name to anneal on")
    parser.add_argument("--phase-name", default=DEFAULT_PHASE_NAME)
    parser.add_argument("--fork-run-id", default=None, help="optional run_id for the release branch")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        manifest = RunManifest.model_validate_json(Path(args.manifest).read_text(encoding="utf-8"))
        cfg = load_run_config(args.config, *args.overlay)
        result = fork_release(
            args.checkpoint,
            args.out,
            manifest=manifest,
            cfg=cfg,
            anneal_dataset=args.anneal_dataset,
            decay_tokens=args.decay_tokens,
            effective_window=args.effective_window,
            committed_block=args.committed_block,
            phase_name=args.phase_name,
            fork_run_id=args.fork_run_id,
        )
    except (ForkError, FileExistsError, FileNotFoundError, ValueError) as exc:
        print(f"release fork failed: {exc}", file=sys.stderr)
        return 2
    print(f"forked manifest : {result.manifest_path}")
    print(f"manifest_hash   : {result.manifest.manifest_hash()}")
    print(f"decay start step: {result.decay_start_step} (peak_lr {result.peak_lr})")
    print(f"runbook         : {result.runbook_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
